/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nomer1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Praktikan
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kodeBuku = new javax.swing.JTextField();
        judulBuku = new javax.swing.JTextField();
        tglTerbit = new javax.swing.JTextField();
        pengarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        inputBuku = new javax.swing.JButton();
        updateBuku = new javax.swing.JButton();
        deleteBuku = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        kelas = new javax.swing.JComboBox();
        lakiLaki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        inputSiswa = new javax.swing.JButton();
        updateSiswa = new javax.swing.JButton();
        deleteSiswa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        kodePinjam = new javax.swing.JTextField();
        kodeBuku2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Nim2 = new javax.swing.JTextField();
        inputPeminjaman = new javax.swing.JButton();
        updatePeminjaman = new javax.swing.JButton();
        deletePeminjaman = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePeminjaman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Perpustakaan Sekolah");

        jLabel2.setText("Data Buku");

        jLabel3.setText("Kode Buku");

        jLabel4.setText("Judul Buku");

        jLabel5.setText("Tgl Terbit");

        jLabel6.setText("Pengarang");

        kodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeBukuActionPerformed(evt);
            }
        });

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul Buku", "Tgl Terbit", "Pengarang"
            }
        ));
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBuku);

        inputBuku.setText("Input");
        inputBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBukuActionPerformed(evt);
            }
        });

        updateBuku.setText("Update");
        updateBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBukuActionPerformed(evt);
            }
        });

        deleteBuku.setText("Delete");
        deleteBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBukuMouseClicked(evt);
            }
        });
        deleteBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(judulBuku)
                                    .addComponent(tglTerbit)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(pengarang))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(kodeBuku)))
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputBuku)
                        .addGap(18, 18, 18)
                        .addComponent(updateBuku)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBuku)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tglTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBuku)
                    .addComponent(updateBuku)
                    .addComponent(deleteBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setText("Siswa");

        jLabel8.setText("Nim");

        jLabel9.setText("Nama");

        jLabel10.setText("Kelas");

        jLabel11.setText("Jenis Kelamin");

        kelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "D3IF-41-01", "D3IF-41-02", "D3IF-41-03", "D3IF-41-04" }));

        lakiLaki.setText("LAKI-LAKI");
        lakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiActionPerformed(evt);
            }
        });

        perempuan.setText("PEREMPUAN");

        inputSiswa.setText("Input");
        inputSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSiswaActionPerformed(evt);
            }
        });

        updateSiswa.setText("update");
        updateSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSiswaActionPerformed(evt);
            }
        });

        deleteSiswa.setText("Delete");
        deleteSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSiswaActionPerformed(evt);
            }
        });

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nim", "Nama", "Kelas", "Jenis Kelamin"
            }
        ));
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSiswa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(inputSiswa))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nim)
                            .addComponent(nama)
                            .addComponent(kelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lakiLaki)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(updateSiswa)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(perempuan)
                                    .addComponent(deleteSiswa)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lakiLaki)
                    .addComponent(perempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSiswa)
                    .addComponent(updateSiswa)
                    .addComponent(deleteSiswa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel12.setText("Peminjaman");

        jLabel13.setText("Kode Pinjam");

        jLabel14.setText("kode Buku");

        jLabel15.setText("NIM");

        jLabel16.setText("Tgl Peminjaman");

        kodePinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodePinjamActionPerformed(evt);
            }
        });

        inputPeminjaman.setText("Input");

        updatePeminjaman.setText("Update");

        deletePeminjaman.setText("Delete");

        tablePeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Peminjaman", "Kode Buku", "Judul", "NIM", "Nama Siswa", "Tanggal Peminjaman ", "tanggal Pengembalian"
            }
        ));
        jScrollPane3.setViewportView(tablePeminjaman);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kodeBuku2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nim2)
                            .addComponent(kodePinjam)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(inputPeminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatePeminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletePeminjaman)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(kodePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(kodeBuku2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Nim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputPeminjaman)
                            .addComponent(updatePeminjaman)
                            .addComponent(deletePeminjaman)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeBukuActionPerformed

    private void inputBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBukuActionPerformed
       if(kodeBuku.getText().trim().equals("")||
          judulBuku.getText().trim().equals("")||
          tglTerbit.getText().trim().equals("")||
          pengarang.getText().trim().equals("")){
          JOptionPane.showMessageDialog(null,"lengkapi data ");
        
    }
        else{
            DefaultTableModel model = (DefaultTableModel) tableBuku.getModel();
            model.addRow(new Object[]{
               kodeBuku.getText(),
               judulBuku.getText(),
               tglTerbit.getText(),
               pengarang.getText(),
            
            });
            JOptionPane.showMessageDialog(null,"data berhasil di simpan");
            
        }
                
    }//GEN-LAST:event_inputBukuActionPerformed
   
    private void lakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiActionPerformed

    private void kodePinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodePinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodePinjamActionPerformed

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
       DefaultTableModel model = (DefaultTableModel) tableBuku.getModel();
       kodeBuku.setText(model.getValueAt( tableBuku.getSelectedRow(),0).toString());
       judulBuku.setText(model.getValueAt(tableBuku.getSelectedRow(),0).toString());
       tglTerbit.setText(model.getValueAt(tableBuku.getSelectedRow(),0).toString());
       pengarang.setText(model.getValueAt(tableBuku.getSelectedRow(),0).toString());
       
    }//GEN-LAST:event_tableBukuMouseClicked

    private void deleteBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBukuMouseClicked
       DefaultTableModel model = (DefaultTableModel) tableBuku.getModel();
       if(tableBuku.getRowCount()==0){
           JOptionPane.showMessageDialog(null,"tabel kosong");
       }else if(tableBuku.getSelectedRow()==-1){
           JOptionPane.showMessageDialog(null, "pilih data akan dihapus : ");
       }
       else{
           int dialogButton = JOptionPane.YES_NO_OPTION;
           int dialogResult = JOptionPane.showConfirmDialog(null,"Anda yakin akan Menghapus");
           if(dialogResult == JOptionPane.YES_OPTION){
               model.removeRow(tableBuku.getSelectedRow());
           }
       }
               
    }//GEN-LAST:event_deleteBukuMouseClicked

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
       DefaultTableModel model = (DefaultTableModel) tableSiswa.getModel();
       nim.setText(model.getValueAt( tableSiswa.getSelectedRow(),0).toString());
       nama.setText(model.getValueAt(tableSiswa.getSelectedRow(),0).toString());
       String jk = model.getValueAt(tableSiswa.getSelectedRow(),3).toString();
       if(jk.equalsIgnoreCase("Laki-Laki")){
           lakiLaki.setSelected(true);
           
       }
       perempuan.setSelected(true);
       
       String clas = model.getValueAt(tableSiswa.getSelectedRow(),4).toString();
       for(int i=0;i<kelas.getItemCount(); i++ ){
           if(clas.equalsIgnoreCase((String)kelas.getItemAt(i))){
           kelas.setSelectedIndex(i);
       }
       }
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void inputSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSiswaActionPerformed
          if(nim.getText().trim().equals("")||
           nama.getText().trim().equals("")||
           (lakiLaki.isSelected() && perempuan.isSelected())){
           JOptionPane.showMessageDialog(null,"lengkapi data ");
        
        }
        else{
            String  kelamin = null;
            if(lakiLaki.isSelected()){
                kelamin="laki laki";
            }else if(perempuan.isSelected()){
                kelamin="perempuan";
            }
            DefaultTableModel model = (DefaultTableModel) tableSiswa.getModel();
            model.addRow(new Object[]{
               nim.getText(),
               nama.getText(),
               kelamin,
               kelas.getSelectedItem().toString()
            
            });
            JOptionPane.showMessageDialog(null,"data berhasil di simpan");
        }
                
    }//GEN-LAST:event_inputSiswaActionPerformed

    private void deleteSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSiswaActionPerformed
       DefaultTableModel model = (DefaultTableModel) tableSiswa.getModel();
       if(tableSiswa.getRowCount()==0){
           JOptionPane.showMessageDialog(null,"tabel kosong");
       }else if(tableSiswa.getSelectedRow()==-1){
           JOptionPane.showMessageDialog(null, "pilih data akan dihapus : ");
       }
       else{
           int dialogButton = JOptionPane.YES_NO_OPTION;
           int dialogResult = JOptionPane.showConfirmDialog(null,"Anda yakin akan Menghapus");
           if(dialogResult == JOptionPane.YES_OPTION){
               model.removeRow(tableSiswa.getSelectedRow());
           }
       }
    }//GEN-LAST:event_deleteSiswaActionPerformed

    private void updateBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBukuActionPerformed
        if(tableBuku.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"table kosong");
        }else if(tableBuku.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"pilih data yang ingin di update");
        }else{
            DefaultTableModel model = (DefaultTableModel) tableBuku.getModel();
            model.setValueAt(kodeBuku.getText(),tableBuku.getSelectedRow(),0);
            model.setValueAt(judulBuku.getText(), tableBuku.getSelectedRow(),0);
            model.setValueAt(tglTerbit.getText(), tableBuku.getSelectedRow(),0);
            model.setValueAt(pengarang.getText(), tableBuku.getSelectedRow(),0);
        }
        JOptionPane.showMessageDialog(null,"data berhasil di simpan");
    }//GEN-LAST:event_updateBukuActionPerformed

    private void deleteBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBukuActionPerformed
       if(tableBuku.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"table kosong");
        }else if(tableBuku.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"pilih data yang ingin di update");
        }else{
            
            DefaultTableModel model = (DefaultTableModel) tableSiswa.getModel();
            model.setValueAt(kodeBuku.getText(),tableSiswa.getSelectedRow(),0);
            model.setValueAt(judulBuku.getText(), tableSiswa.getSelectedRow(),0);
           
            model.setValueAt(tglTerbit.getText(),tableSiswa.getSelectedRow(),0);
            model.setValueAt(pengarang.getText(), tableSiswa.getSelectedRow(),0);
            tableSiswa.clearSelection();
        }
        JOptionPane.showMessageDialog(null,"data berhasil di simpan");
    }//GEN-LAST:event_deleteBukuActionPerformed

    private void updateSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSiswaActionPerformed
        if(tableSiswa.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"table kosong");
        }else if(tableSiswa.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"pilih data yang ingin di update");
        }else{
            String rbKelamin = null;
            if(lakiLaki.isSelected()){
                rbKelamin="laki-laki";
            }
            else if(perempuan.isSelected()){
                rbKelamin="perempuan";
            }
            DefaultTableModel model = (DefaultTableModel) tableSiswa.getModel();
            model.setValueAt(nim.getText(),tableSiswa.getSelectedRow(),0);
            model.setValueAt(nama.getText(), tableSiswa.getSelectedRow(),0);
            model.setValueAt(rbKelamin, tableSiswa.getSelectedRow(),3);
            model.setValueAt(kelas.getSelectedItem(), tableSiswa.getSelectedRow(),4);
            tableSiswa.clearSelection();
        }
        JOptionPane.showMessageDialog(null,"data berhasil di simpan");
    }//GEN-LAST:event_updateSiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nim2;
    private javax.swing.JButton deleteBuku;
    private javax.swing.JButton deletePeminjaman;
    private javax.swing.JButton deleteSiswa;
    private javax.swing.JButton inputBuku;
    private javax.swing.JButton inputPeminjaman;
    private javax.swing.JButton inputSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField judulBuku;
    private javax.swing.JComboBox kelas;
    private javax.swing.JTextField kodeBuku;
    private javax.swing.JTextField kodeBuku2;
    private javax.swing.JTextField kodePinjam;
    private javax.swing.JRadioButton lakiLaki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField pengarang;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTable tablePeminjaman;
    private javax.swing.JTable tableSiswa;
    private javax.swing.JTextField tglTerbit;
    private javax.swing.JButton updateBuku;
    private javax.swing.JButton updatePeminjaman;
    private javax.swing.JButton updateSiswa;
    // End of variables declaration//GEN-END:variables
}
